### PR TITLE
SRVKP-5855: remove (via rename) update pipeline-service PAC jobs

### PR DESCRIPTION
**Pull request by gabemontero**
moving instead of remove so we can more easily revisit this stuff in the future if need be

rh-pre-commit.version: 2.3.0
rh-pre-commit.check-secrets: ENABLED

### CODE REVIEW

**Review by avinal — APPROVED** [review]

**Comment by enarha** [comment]
@gabemontero Shouldn't we make that update infra-deployments until we switch to installing Results through the operator? The alternative is to manage those refs manually from infra-deployments.

**Comment by gabemontero** [comment]
> @gabemontero Shouldn't we make that update infra-deployments until we switch to installing Results through the operator? The alternative is to manage those refs manually from infra-deployments.

This in my opinion @enarha goes hand in hand with https://github.com/openshift-pipelines/pipeline-service/pull/1034 which you lgtm'ed

And yes, it means updates to the results images area made manually, presumably by the Konflux team when they decide to upgrade.  We are not initiating changes for them.  

However, until the install of results is via the operator, the Konflux team would have to monitor this repo in addition to whatever you'll set up for them so they can decide which nightlies to pick.

All this said, I'm fine with holding on this for now if you want, given the relative lack of activity.  You decide how to proceed since I'll be leaving soon.

https://github.com/redhat-appstudio/infra-deployments/pull/4291 is the key PR to merge.

**Comment by enarha** [comment]
> > @gabemontero Shouldn't we make that update infra-deployments until we switch to installing Results through the operator? The alternative is to manage those refs manually from infra-deployments.
> 
> This in my opinion @enarha goes hand in hand with [openshift-pipelines/pipeline-service#1034](https://github.com/openshift-pipelines/pipeline-service/pull/1034) which you lgtm'ed
> 
> And yes, it means updates to the results images area made manually, presumably by the Konflux team when they decide to upgrade. We are not initiating changes for them.
> 
> However, until the install of results is via the operator, the Konflux team would have to monitor this repo in addition to whatever you'll set up for them so they can decide which nightlies to pick.
> 
> All this said, I'm fine with holding on this for now if you want, given the relative lack of activity. You decide how to proceed since I'll be leaving soon.
> 
> [redhat-appstudio/infra-deployments#4291](https://github.com/redhat-appstudio/infra-deployments/pull/4291) is the key PR to merge.

I see this one (and the respective jobs in the metrics exporter) differently from the jobs in pipeline-service. This one could switch to updating infra-deployment, the one from pipeline-service we want to disable sooner. With that being said, I agree, lets focus on 4291. I'll review it later today.

**Comment by gabemontero** [comment]
I'm going to close this out @enarha and let you all decide on manually updating the refs in infra-deployments or modifying the update jobs to modify the yaml files in infra-deployments (moving the resuts yaml out of the main yaml file might be needed to make the regex more tenable).

**Comment by enarha** [comment]
> I'm going to close this out @enarha and let you all decide on manually updating the refs in infra-deployments or modifying the update jobs to modify the yaml files in infra-deployments (moving the resuts yaml out of the main yaml file might be needed to make the regex more tenable).

Thanks. I'm working on switching the Results installation through the operator, so that won't be needed at all.

**Pull request closed without merging**
