### PR TITLE
DO NOT MERGE, CI ONLY Downstream 0.7.0-01

### PR DESCRIPTION
**Pull request by avinal**
## New Features

- Install: add option for localhost DNS name
- Add overlay for enabling logs
- Add recovery middleware to gRPC server
- Add option to enable Prometheus histogram
- Add GolangCI via Makefile + Presubmit.sh

## Changes that require updates to our deployment configuration

- [downstream change] added new overlay for base-only deployment

## Breaking changes
None

## Other Changes
- Restore cleanup after e2e tests 
- Fixes for YAML Lints

### CODE REVIEW

**Comment by enarha** [comment]
You are missing the "Add GolangCI via Makefile + Presubmit.sh" change from the description. It's important not only because it introduced linters, but also because it made the code compliant to those linters, so IMO it's worth mentioning.

Did we really introduce any new upstream changes that require "added new overlay for base-only deployment"? I understand the need to cleanup our downstream kustomizations, my question is if it is a direct requirement from the new changes.

The rest is LGTM.

**Comment by avinal** [comment]
@enarha I have split the changes into a carry commit and a new commit as discussed.

**Comment by enarha** [comment]
Now that I see your change for adding the base overlay, I really think upstream is a better place for it. Having said that, we probably won't require it for long time. Switching to operator install will make it redundant, so I'm OK to leave it as is. Bottom line is, if you think that overlay will benefit upstream users, you can add it upstream, otherwise leave it as is.

/lgtm

**Review by sayan-biswas — APPROVED** [review]

**Comment by avinal** [comment]
Thank you closing this PR

**Pull request closed without merging**
