### PR TITLE
KCP changes for API server

### PR DESCRIPTION
**Pull request by sayan-biswas**
API sever changes to work with KCP clusters. Will unit add test for KCP methods in separate PR.
Authentication -> Cluster in the request used (consumer/user workspace)
Authorisation -> Always in KCP pipeline service cluster (this can be extended to a 2nd level of RBAC on the requested cluster)

### CODE REVIEW

**Comment by adambkaplan** [comment]
@sayan-biswas I merged the S3 pull request in, which means you probably need to rebase and re-vendor your code.

**Comment by sayan-biswas** [comment]
> @sayan-biswas I merged the S3 pull request in, which means you probably need to rebase and re-vendor your code.

I have rebased and re-vendor to the latest code. Although, I haven't test the S3 functionalities. Few KCP related changes were made to the log handlers.

@avinal Please go through the changes and you can use this to rebase your kcp-aware-watcher PR.

**Review by adambkaplan — CHANGES_REQUESTED** [review]
I hate to ask that you effectively re-do this PR, but there are several inter-mixed changes here that will make our lives difficult in the long run. Ideally, all KCP-related changes are self-contained in a few commits that we can cherry-pick each time we rebase Tekton Results from upstream.

There are  few changes/fixes here which are not KCP related, such as renaming `conf` to `config`, fixing the DB schema sql file, reordering the methods in the .proto files, etc. These should be isolated into separate commits so that we can get them merged upstream.

**Review by sayan-biswas — COMMENTED** [review]
@adambkaplan I have reverted the additional changes. Please review and let me know if I any other changes are needed. The DB schema change is required, because the **parent** field was limited to 63 chars, and some cluster names wont fit in there.  The only other unnecessary change was the **name** field in the **UpdateResultRequest**, which was redundant.

**Review by adambkaplan — APPROVED** [review]
Marking this as LGTM.

@avinal if there are no objections from you I think we should merge this.

**Comment by avinal** [comment]
Seems good to me as well. @adambkaplan

**Review by avinal — APPROVED** [review]

**Pull request merged**
