### PR TITLE
DO NOT MERGE, CI ONLY: Downstream 0.9.1 01

### PR DESCRIPTION
**Pull request by avinal**
## New features
- [implementation for summary of list of records](https://github.com/openshift-pipelines/tektoncd-results/commit/456ba20b10c74f54e74281547b9b87589dcae060)
- [handle all terminal states when processing logs](https://github.com/openshift-pipelines/tektoncd-results/commit/905e9b5d1cba387ac48a79a2a3fbf630ff693d45)

## Changes that require update to our downstream configuration
- [Remove Config Values as Env var in API server](https://github.com/openshift-pipelines/tektoncd-results/commit/ed1ffdbe7fcd0733623050e4aa460afadb938e40)

## Breaking changes
- [Remove Config Values as Env var in API server](https://github.com/openshift-pipelines/tektoncd-results/commit/ed1ffdbe7fcd0733623050e4aa460afadb938e40)

### CODE REVIEW

**Review by gabemontero — COMMENTED** [review]
Am I correct @avinal that your summary of list records change https://github.com/openshift-pipelines/tektoncd-results/commit/456ba20b10c74f54e74281547b9b87589dcae060 only adds to the API and should not affect the Konflux UI?

as we have broken them with recent API change we need to be careful

also, I forget, was that added to assist the Konflux UI?  If so, have they been properly alerted in one of their Jira's that it is coming?

otherwise, lgtm thanks

**Comment by avinal** [comment]
Correct this is only an addition to the API and nothing else has changed. The feature request was from Openshift dashboard team. But it can be used by Konflux UI as well. No jira so far.

**Review by ramessesii2 — APPROVED** [review]

**Review by gabemontero — APPROVED** [review]
/lgtm

**Comment by gabemontero** [comment]
As I still wouldn't consider myself fluent with this downstreaming process @avinal I'm going to defer to you or @enarha to hit the merge button

**Comment by gabemontero** [comment]
sorry you all don't hit the merge button :-) 
you close out right ?

**Comment by avinal** [comment]
Yes, we close and push another branch. I will do that now.

**Comment by avinal** [comment]
downstream-v0.9.1-01 branch pushed and made default

**Pull request closed without merging**
