### PR TITLE
DO NOT MERGE: Downstream 0.8.0 02

### PR DESCRIPTION
**Pull request by avinal**
# New Features
- [Fix] [Make sure gRPC connection is closed](https://github.com/openshift-pipelines/tektoncd-results/commit/0aa7ce4900d905dfac265bd8542e99bda451d4c7)
- [Fix] [Fix SAR groups and Extra](https://github.com/openshift-pipelines/tektoncd-results/pull/54/commits/56c15b20e2827f9723581298d7b0d60edaad4f23)
- [Enhance] [Improve watcher logs](https://github.com/openshift-pipelines/tektoncd-results/pull/54/commits/e203c93459719a8eb91118e5892fc6c1663eb246)
# Changes that requires update to our deployment config
N/A

# Breaking changes
N/A

### CODE REVIEW

**Comment by avinal** [comment]
Brnach pushed https://github.com/openshift-pipelines/tektoncd-results/tree/downstream-0.8.0-02 closing as completed

**Comment by avinal** [comment]
Branch pushed https://github.com/openshift-pipelines/tektoncd-results/tree/downstream-0.8.0-02 closing as completed

**Comment by avinal** [comment]
Reopening and updating since not updated in Pipeline service.

**Review by sayan-biswas — APPROVED** [review]

**Review by ramessesii2 — APPROVED** [review]

**Comment by avinal** [comment]
The last commit is redundant and empty, will skip it while pushing.

**Comment by avinal** [comment]
The last commit is redundant and empty, will skip it while pushing.

**Pull request closed without merging**
