### PR TITLE
DO NOT MERGE, CI ONLY Downstream 0.6.0 01

### PR DESCRIPTION
**Pull request by avinal**
## New Features
- Allow users/integrators to pass arbitrary keys/values through Result and RecordSummary annotations
- Make e2e tests more configurable
- Enhance search capabilities by implementing an engine to convert CEL expressions to SQL equivalent filters.
- api: Add healthz endpoint to enable liveness, readiness, and startup probes for the api-server deployment. Default configuration uses HTTP, but gRPC can also be used.
- api: Poll up to two minutes when establishing the database connection.
  

## Changes that require updates to our deployment configuration
None

## Breaking changes
- the fields created_time and updated_time  are no longer valid to order Results  and Records through list operations. If you want to sort those objects by timestamps, use the create_time and update_time instead. Those fields mirror the same attributes present in the wire representation of Results and Records. 

## Others
- Fix version tag for results release
- Update kustomization files to latest standard
- Bump gorm.io/gorm from 1.24.3 to 1.25.0
- Bump go version to 1.19
- Bump google.golang.org/grpc from 1.53.0 to 1.55.0
- Bump k8s.io/api from 0.25.8 to 0.25.9
- [CARRY]: Tekton Results downstream configuration

### CODE REVIEW

**Comment by avinal** [comment]
cc @prietyc123

**Comment by prietyc123** [comment]
I have only concern as in pr https://github.com/openshift-pipelines/tektoncd-results/pull/43#discussion_r1193512431 
Otherwise everything looks good 👍

**Comment by enarha** [comment]
@prietyc123 is right, the description does not indicate new features/configuration update required/breaking changes as per the downstream sync doc. Two of the included changes are to be considered new features IMO.
The rest is LGTM, the right upstream changes are included and the downstream commit as well.
/lgtm

**Comment by gabemontero** [comment]
> @prietyc123 is right, the description does not indicate new features/configuration update required/breaking changes as per the downstream sync doc. Two of the included changes are to be considered new features IMO. The rest is LGTM, the right upstream changes are included and the downstream commit as well. /lgtm

+1 `Allow users/integrators to pass arbitrary keys/values through Result and RecordSummary annotation` is certainly a new feature

**Comment by adambkaplan** [comment]
Since we have this PR open to iterate on - worth calling out that we aren't getting snyk scan results from our pipeline definitions. See https://issues.redhat.com/browse/PLNSRVCE-1315

**Comment by avinal** [comment]
Updated PR description. 

> Since we have this PR open to iterate on - worth calling out that we aren't getting snyk scan results from our pipeline definitions.

Should I investigate into this issue?

**Comment by avinal** [comment]
> @prietyc123 is right, the description does not indicate new features/configuration update required/breaking changes as per the downstream sync doc.

I will add the suggestions in the carry patch.

**Comment by adambkaplan** [comment]
@avinal it appears that there are some missing fixes in the pipeline definitions - currently indicates that there are conflicting files.

**Comment by avinal** [comment]
I will have to see if there are missing updates. The conflicts are expected since the changes are rebased and not mergable. It shouldn't be an issue because we are only changing our downstream configs, and it will go to a different branch.

**Comment by enarha** [comment]
LGTM

**Comment by gabemontero** [comment]
/lgtm

my additions to impersonation/authorization error messages is in here - cool deal

**Comment by avinal** [comment]
Thanks for reviewing. I have pushed the new branch https://github.com/openshift-pipelines/tektoncd-results/tree/downstream-0.6.0-01. Closing this PR

**Pull request closed without merging**
