### PR TITLE
DO NOT MERGE, CI ONLY: Downstream 0.9.2 01

### PR DESCRIPTION
**Pull request by gabemontero**
## New Features

[Disable Proxy for Rest to GRPC communication](https://github.com/tektoncd/results/commit/32314594d4e5cf6de35e13cb7429ae216a969781)

[Update database drivers](https://github.com/tektoncd/results/commit/ea628ea1751cc9a889ffed5b16231d6fc5eede11)

[Don't run auth check for every log fragment](https://github.com/tektoncd/results/commit/c37ca39718bfd8f631268bb5aa9a7ca221a6155f)

[Add profiling to API server](https://github.com/tektoncd/results/commit/e7a9ab58e0cae3009210a77510b9cd20d4f33975)

[Fix golang lint](https://github.com/tektoncd/results/commit/9a1dbbc0f872aeb71e60d3d4142be6481a63f9f4)

[encapsulate all grpc calls from dynamic reconciler with cancelling conext with timeout](https://github.com/tektoncd/results/commit/aa5bb71f7f031ae6e16ca7819c531ac5891d2842)

[Update golang.org/x/net to handle CVE GO-2024-2687](https://github.com/tektoncd/results/commit/9309cee5d2c4a83dc145999d95e087fa814aee68)

[alllow for database connection, grpc worker thread pool, and k8s client level tuning of the watcher and api servers](https://github.com/tektoncd/results/commit/714dfd2c0b9775251036905cb2f803e81d14f861)

## Breaking Changes

None

## Changes that requires update to our downstream configuration

None  (we are picking up non-required changes that we will want to leverage

downstream-0.9.1-03 was the only one I was able to merge to without conflicts @sayan-biswas @enarha @avinal 

PTAL

### CODE REVIEW

**Review by avinal — APPROVED** [review]
Looks good to me. I think [alllow for database connection, grpc worker thread pool, and k8s client level tuning of the watcher and api servers](https://github.com/tektoncd/results/commit/714dfd2c0b9775251036905cb2f803e81d14f861) should be listed separately as it may require some changes to our downstream config.

**Comment by gabemontero** [comment]
> Looks good to me. I think [alllow for database connection, grpc worker thread pool, and k8s client level tuning of the watcher and api servers](https://github.com/tektoncd/results/commit/714dfd2c0b9775251036905cb2f803e81d14f861) should be listed separately as it may require some changes to our downstream config.

sorry @avinal  I'm not following what you mean by "listed separately

the commit is separate, and I list it explicitly in the description

can you clarify?

**Comment by avinal** [comment]
@gabemontero I was talking about PR description: https://github.com/openshift-pipelines/tektoncd-results/blob/downstream-0.9.1-04/downstream.md?plain=1#L39-L42 not a blocker, you can go ahead and push the branch once there is one more approval.

**Comment by gabemontero** [comment]
> @gabemontero I was talking about PR description: https://github.com/openshift-pipelines/tektoncd-results/blob/downstream-0.9.1-04/downstream.md?plain=1#L39-L42 not a blocker, you can go ahead and push the branch once there is one more approval.

ah gotcha thanks @avinal 

PR description updated

bump @enarha @sayan-biswas

**Comment by enarha** [comment]
lgtm
IMo you can do forward, close the PR and push the branch.

**Comment by enarha** [comment]
/hold
I just need to verify sth

**Comment by enarha** [comment]
/unhold
all clear.

**Comment by gabemontero** [comment]
> lgtm IMo you can do forward, close the PR and push the branch.

sorry @enarha not sure what you mean by "do forward" ... can you clarify?

searching for `forward` in https://github.com/openshift-pipelines/tektoncd-results/blob/downstream-0.9.1-04/downstream.md I only see one instance of `forward` and it is talking about how the fast-forward feature helps.

**Comment by enarha** [comment]
I meant consider this change +2 (me and Avinal) and proceed with the next steps of the process which are to close the PR, push the branch and make it default. Apologies for not being clear.

**Comment by gabemontero** [comment]
> I meant consider this change +2 (me and Avinal) and proceed with the next steps of the process which are to close the PR, push the branch and make it default. Apologies for not being clear.

no worries / thanks

**Pull request closed without merging**
