### PR TITLE
fix pipeline-service update pipelinerun

### PR DESCRIPTION
**Pull request by avinal**
- tekton results directory in pipeline service is restructured

### CODE REVIEW

**Comment by enarha** [comment]
We need #49 merged first to fix the CI.

**Comment by gabemontero** [comment]
@enarha so https://github.com/openshift-pipelines/tektoncd-results/pull/49 has now merged

do we still need this?

/retest

**Comment by enarha** [comment]
@gabemontero yes, I think we do. @avinal ?

**Comment by avinal** [comment]
Yes the path is incorrect in the script.

**Pull request merged**
